image: maven:3.6.0-jdk-8

stages:
  - Build
  - Deploy

Build:
  stage: Build
  script:
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml versions:set -DprocessAllModules=true -DnewVersion=$CI_COMMIT_REF_NAME
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml clean install
  except:
    - tags

Deploy:
  stage: Deploy
  script:
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml versions:set -DprocessAllModules=true -DnewVersion=$CI_COMMIT_REF_NAME
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml clean deploy
  only:
    - tags


