image: maven:3.6.0-jdk-8

stages:
  - Build
  - Deploy

before_script:
  - export VERSION=`git describe origin/$CI_COMMIT_REF_NAME`

Build:
  stage: Build
  script:
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml versions:set -DprocessAllModules=true -DnewVersion=$VERSION
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml clean install

Deploy:
  stage: Deploy
  script:
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml versions:set -DprocessAllModules=true -DnewVersion=$VERSION
    - mvn -s ${CI_PROJECT_DIR}/maven-settings.xml clean deploy
  only:
    - /^release-.*$/


